### ISSUE TITLE
Particle animations leak memory

### ISSUE THREAD

**Issue by Dzarg** [Meelo/NALCG#10]
Blood and burning animations leak memory. Queen's attack animation might even have other leaking components. Something should be done to prevent this.

**Comment by Meelo** [comment]
Grhm, upgraded from Nice-to-have to Critical.

**Comment by Dzarg** [comment]
The leaks should now be considerably lower than previously. There is however still some memory leaking in the game even with the bishop animation, but I think it's not an issue with particle animations anymore. Opened a new ticket #14 for it.

**Comment by Meelo** [comment]
Confirmed on Linux, no leakage detected.
