### ISSUE TITLE
Big Bang animation when view is created for the first time

### ISSUE THREAD

**Issue by Meelo** [Meelo/NALCG#12]
First there was darkness,
Then came the big bang,
And everything appeared.

**Comment by Dzarg** [comment]
Created with zooming animation. Let's hope it plays well enough on average computers.

**Comment by Meelo** [comment]
Worked well enough on my laptop which as you know, runs on Linux with horrible ATI OpenGL drivers.

**Comment by Dzarg** [comment]
The animation played ok on university computers, but froze for a bit when the ground is created at about 1.5 seconds to the animation. 60c4bd5a87f95d5ec8ae2354977d1b976e6d2d02 fixes this freezing.
