### ISSUE TITLE
Still some memory leaks exist in the game

### ISSUE THREAD

**Issue by Dzarg** [Meelo/NALCG#14]
The game still seems to leak some memory. At least on Windows it seems to be around few kilobytes per bishop attack. Not nearly as critical as it was before, but it should still be investigated. #10 is a related ticket which took care of most of the leaks.

**Comment by Meelo** [comment]
Kept flying back and forth with queens for a few minutes, after like 20 moves, memory usage jumped 4M, but I couldn't reproduce such behaviour. No noticable difference with other  animations.

I change this task's status to 'undefined'. Change it back to important or critical if the leakage can be confirmed.

**Comment by Dzarg** [comment]
Now I think I might have caught all the leaks.
