### ISSUE TITLE
A way of sending message to a specific EndUser

### ISSUE THREAD

**Issue by Meelo** [Meelo/NALCG#15]
Should be able to inform the specific EndUser who originally sent a command to Middleman, that there was some sort of error with the request. Invalid move, wrong turn, etc.

**Comment by Dzarg** [comment]
I think the function return value should be sufficient for this task.

**Comment by Meelo** [comment]
But EndUser does not receive a return value from Middleman. Should it? move() returns boolean, and that is not sufficient for most error scenarios.

**Comment by Dzarg** [comment]
It should then probably return an enum, normal int or an int mask. Int mask might be good if we want show both invalid move and wrong turn at the same time.

**Comment by Meelo** [comment]
okay let's see what kind of messages are needed..

1 - Invalid move
2 - Invalid turn
3 - Promotion

Anything else?
