### ISSUE TITLE
Pawn promotion

### ISSUE THREAD

**Issue by Meelo** [Meelo/NALCG#18]
When pawn reaches the opposite end of the board, it can be promoted to rook, bishop, knight or queen. This needs to be implemented.

**Comment by Meelo** [comment]
Done, view doesn't realise this yet. Needs a special message.

**Comment by Dzarg** [comment]
Very basic functionality done. Now it can at least be played. Next improvement would be to make a pawn promoted to queen actually look like a queen and not pawn :)

**Comment by Dzarg** [comment]
It's almost done now, some effects or animations might still be needed.

**Comment by Dzarg** [comment]
Done
