### ISSUE TITLE
Pawn movement/attack animation

### ISSUE THREAD

**Issue by Meelo** [Meelo/NALCG#8]
Something wicked should happen when pawn kills people. Original idea was an axe throwing animation, where pawn throws his axe at the target.

This how ever has a problem, en passant -move would make the animation throw at empty slot, and view most likely won't even notice that dying unit.

**Comment by Dzarg** [comment]
Moved this issue to critical state as it's critical that this is resolved one way or another.

**Comment by Dzarg** [comment]
There's now cool pacman summoning animation ;)
